### 单词速记

- manipulate 操作
- complex 复杂
- flexible 灵活的
- argument （参数）
- metadata 元数据
- album 专辑，相册
- format 版本，格式
- Accessing Nested Objects 访问嵌套对象
- Iterate with JavaScript For Loops JavaScript循环迭代
- Algorithm 算法
- declare 声明
- netst 嵌套